### ISSUE TITLE
No color with my theme

### ISSUE THREAD

**Issue by jasonbhimani** [dracula/terminal-app#14]
I downloaded the theme on my terminal and am trying to make it look like what's on the website but it isn't working. Can someone help? I'm also very new to all this, it's my first time using terminal so please be specific on anything I need to do. Even when I type in certain words such as git it doesn't work. Thank you in advance. 

<img width="726" alt="Screen Shot 2020-06-30 at 11 57 14 AM" src="https://user-images.githubusercontent.com/36485528/86148607-db147d00-bac8-11ea-90e6-5f4acf770654.png">

<img width="568" alt="Screen Shot 2020-06-30 at 11 55 53 AM" src="https://user-images.githubusercontent.com/36485528/86148474-a99bb180-bac8-11ea-8a06-97730c38ddf4.png">

**Comment by benknoble** [comment]
@jasonbhimani Thanks for using the theme! Starting your terminal journey is an exciting time, and I’m so excited for everything you have to learn!

I want to point you to some resources from this repo and give you some things to think about. Most terminal programs (and that includes shells) don’t colorize their output by default (with the exception of the ones that are designed too). That’s because colors require special escape sequences in the output that other programs don’t need—they’re for the terminal only.

So, you will probably need to configure your shell, git, and other tools to display colors (but only when displaying on the terminal). There are so many great resources for this, and they are all a search away!

I’ll mention a few related ones here: There’s some info in #2, #3, #4, #7, #8, #9, and #10.

**Comment by jasonbhimani** [comment]
Hey I read those and actually didn't understand what was going on. I heard the theme comes with the color for basic things like git but even that stays the same color.  I also don't know how to apply colors only for certain things.

**Comment by jasonbhimani** [comment]
Is there a video or form on how to configure the colors?

**Comment by benknoble** [comment]
There are shell themes floating around somewhere (zsh in particular) that may add more color. Prompt settings often include some form of colorization. Some programs accept flags or configuration variables that produce color (see the man pages for those). In particular, try git diff or git status, which colorize by default when outputting to a terminal.

I’m not aware of any good tutorials on color, although googling for something like “shell colors” should get some results. If you find a good one you like, please let me know and I will link to it.

**Comment by logicman** [comment]
Thanks for your comment. I had the same issue. For newbies, this can be something of "oh, the theme is not working!". 
Would be good to have a quick tutorial of sorts etc...cause, I now really don't know what to do after I have applied the "theme" to the Terminal. The background changed, but nothing else. 

Cheers!

**Comment by benknoble** [comment]
@logicman agreed! Please, if anyone has resources like this, let's collect them! I just don't have any on-hand, and I don't have too much time to dig for good ones. Putting color into my terminal was something acquired over time using the terminal, and I didn't keep track of where I got the information at the time :(

**Comment by mdeboute** [comment]
@benknoble I did [that](https://github.com/mdeboute/my_awesome_terminal) to definitively close the subject and help you with those issues :)

**Comment by benknoble** [comment]
@mdeboute un grand merci :) I'll pin this issue or a similar one, so people get here. Perhaps you could link some of the dupes I mentioned on your README?

**Comment by mdeboute** [comment]
@benknoble you're welcome :) I will do that !
