### ISSUE TITLE
Cannot Import Dracula.terminal file

### ISSUE THREAD

**Issue by huseyinham** [dracula/terminal-app#5]
Hi,

Wasn't sure where to raise this 'issue' as I don't think it is something related to the project itself, but after cloning the repo, I cannot import the necessary file (see below). It seems as though it is the terminal.app folder that isn't accessible? 

<img width="726" alt="screen shot 2018-02-19 at 13 42 27" src="https://user-images.githubusercontent.com/18657488/36380601-c3702992-157a-11e8-8874-b3bc59f25758.png">

File structure of cloned repo:
```
hhami@hhamiMBP:~/otherGit/terminal.app$ll
total 32
drwxr-xr-x   7 hhami  staff   224 19 Feb 13:33 .
drwxr-xr-x   3 hhami  staff    96 19 Feb 13:33 ..
drwxr-xr-x  12 hhami  staff   384 19 Feb 13:33 .git
drwxr-xr-x   4 hhami  staff   128 19 Feb 13:33 .github
-rw-r--r--   1 hhami  staff  7624 19 Feb 13:33 Dracula.terminal
-rw-r--r--   1 hhami  staff  1080 19 Feb 13:33 LICENSE
-rw-r--r--   1 hhami  staff   720 19 Feb 13:33 README.md
```
Apologies if I am just being stupid.

**Comment by benknoble** [comment]
Hi @huseyinham , it seems that Finder thinks the directory is an app (due to the extension `.app`). This is preventing you from getting inside it 😢 .

I have two solutions you can try:

1. Rename the directory, removing the `.app` suffix (doable from Finder or with `mv` at the command line)
2. Right click in Finder and choose "Show package contents" (or something similar). You should then be able to get to the `Dracula.terminal` file that you want.

If that helps, please let me know and I'll 
- [x] update the README with that info, 
- [x] try to get it added to the website and
- [x] mark as resolved.

**Comment by huseyinham** [comment]
Ah you're right, that was the issue. I just renamed the folder - and voila! :)

Thanks for the speedy response!

**Comment by zenorocha** [comment]
Done! Repository renamed ;)

Thanks for reporting @huseyinham and thanks for fixing it @benknoble!

**Comment by benknoble** [comment]
@zenorocha Thank dracula for automatic github redirects; I was concerned things might break
